// Typed wrappers around the server registry Tauri commands (TASK-M1-03/05).
// Mirrors the Rust `ServerEntry` / `ServerEntryInput` / `ServerHealth` shapes
// (camelCase) and normalizes rejections to ApiError, following client.ts.

import { invoke } from "@tauri-apps/api/core";
import { ApiError } from "./errors.js";

/** A saved server connection (mirrors the Rust `ServerEntry`). */
export interface ServerEntry {
  id: string;
  name: string;
  url: string;
  username?: string;
  password?: string;
  createdAt: number;
  lastConnectedAt?: number;
}

/** User-supplied fields of a server entry; id and timestamps are generated by the registry. */
export interface ServerEntryInput {
  name: string;
  url: string;
  username?: string;
  password?: string;
}

/** Basic Auth credentials for probes and requests. */
export interface AuthCredentials {
  username?: string;
  password?: string;
}

/** Health snapshot of one server (mirrors the Rust `ServerHealth`). */
export interface ServerHealth {
  serverId: string;
  healthy: boolean;
  version?: string;
  latencyMs?: number;
  lastOk?: number;
  failCount: number;
  status: "ok" | "slow" | "down";
}

export async function listServers(): Promise<ServerEntry[]> {
  return invoke<ServerEntry[]>("list_servers").catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

export async function addServer(input: ServerEntryInput): Promise<ServerEntry> {
  return invoke<ServerEntry>("add_server", { entry: input }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

export async function updateServer(id: string, input: ServerEntryInput): Promise<ServerEntry> {
  return invoke<ServerEntry>("update_server", { id, entry: input }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

export async function removeServer(id: string): Promise<void> {
  return invoke<void>("remove_server", { id }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

/** One-shot health probe against an arbitrary server URL (Add Server flow). */
export async function probeServer(url: string, auth?: AuthCredentials): Promise<ServerHealth> {
  const args = auth ? { url, auth } : { url };
  return invoke<ServerHealth>("probe_server", args).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}
