// Typed wrappers around the server registry Tauri commands (TASK-M1-03/05).
// Mirrors the Rust `ServerEntry` / `ServerEntryInput` / `ServerHealth` shapes
// (camelCase) and normalizes rejections to ApiError, following client.ts.

import { invoke } from "@tauri-apps/api/core";
import { ApiError } from "./errors.js";

/** A saved server connection (mirrors the Rust `ServerEntry`). */
export interface ServerEntry {
  id: string;
  name: string;
  url: string;
  username?: string;
  password?: string;
  oauth?: ServerOAuth;
  /** Whether the desktop app owns the local opencode serve process. */
  mode?: ServerMode;
  createdAt: number;
  lastConnectedAt?: number;
}

export type ServerMode = "remote" | "local";

/** RFC 9728 OAuth credentials stored on a server entry (mirrors the Rust
 *  `ServerOAuth`). Tokens are managed by the Rust side; the frontend only
 *  reads the shape to decide between Basic and OAuth re-auth flows. */
export interface ServerOAuth {
  clientId: string;
  discoveryUrl: string;
  authorizationEndpoint: string;
  tokenEndpoint: string;
  scope?: string;
  accessToken: string;
  refreshToken?: string;
  expiresAt?: number;
}

/** Result of an RFC 9728 discovery (`oauth_discover`). */
export interface OAuthDiscovery {
  authorizationEndpoint: string;
  tokenEndpoint: string;
  clientId?: string;
  scopesSupported?: string[];
}

/** Result of `oauth_authorize`: the URL to open in the system browser. */
export interface OAuthAuthorizeResult {
  authorizationUrl: string;
  redirectUri: string;
  clientId: string;
}

/** Credential state of a server (`oauth_status`). */
export interface OAuthStatus {
  configured: boolean;
  hasRefreshToken: boolean;
}

/** User-supplied fields of a server entry; id and timestamps are generated by the registry. */
export interface ServerEntryInput {
  name: string;
  url: string;
  username?: string;
  password?: string;
  mode?: ServerMode;
}

/** Basic Auth credentials for probes and requests. */
export interface AuthCredentials {
  username?: string;
  password?: string;
}

/** Health snapshot of one server (mirrors the Rust `ServerHealth`). */
export interface ServerHealth {
  serverId: string;
  healthy: boolean;
  version?: string;
  latencyMs?: number;
  lastOk?: number;
  failCount: number;
  status: "ok" | "slow" | "down";
}

export async function listServers(): Promise<ServerEntry[]> {
  return invoke<ServerEntry[]>("list_servers").catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

export async function addServer(input: ServerEntryInput): Promise<ServerEntry> {
  return invoke<ServerEntry>("add_server", { entry: input }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

export async function updateServer(id: string, input: ServerEntryInput): Promise<ServerEntry> {
  return invoke<ServerEntry>("update_server", { id, entry: input }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

export async function removeServer(id: string): Promise<void> {
  return invoke<void>("remove_server", { id }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

/** Starts a saved server configured for app-managed local mode. */
export async function startLocalServer(serverId: string): Promise<number> {
  return invoke<number>("start_local_server", { serverId }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

/** Stops a saved app-managed local server; safe to call during teardown. */
export async function stopLocalServer(serverId: string): Promise<void> {
  return invoke<void>("stop_local_server", { serverId }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

/**
 * One-shot health probe against an arbitrary server URL (Add Server flow).
 * The resolved payload is validated: a server that answers with a non-health
 * body (e.g. an HTML error page or a proxy banner) must not count as a
 * healthy OpenCode server, so the wrapper rejects with an `invalid_response`
 * ApiError instead (TASK-M1-09 defense).
 */
export async function probeServer(url: string, auth?: AuthCredentials): Promise<ServerHealth> {
  const args = auth ? { url, auth } : { url };
  const payload = await invoke<ServerHealth>("probe_server", args).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
  return validateProbePayload(payload);
}

function validateProbePayload(payload: ServerHealth): ServerHealth {
  if (typeof payload !== "object" || payload === null || typeof payload.healthy !== "boolean") {
    throw new ApiError(undefined, "invalid_response", "Unexpected response format", false);
  }
  return payload;
}

/** (Re)starts the 15s health polling loop for a saved server (reconnect flow). */
export async function startHealthMonitoring(serverId: string): Promise<void> {
  return invoke<void>("start_health_monitoring", { serverId }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

/** Discovers the RFC 9728 OAuth metadata of a server URL. Rejects with
 *  a not_found ApiError when the server has no discovery document. */
export async function discoverOAuth(url: string): Promise<OAuthDiscovery> {
  return invoke<OAuthDiscovery>("oauth_discover", { url }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

/** Starts an OAuth authorization for a saved server: generates PKCE +
 *  state (kept in the Rust process), returns the URL to open in the
 *  system browser. The redirect URI is a loopback callback. */
export async function authorizeOAuth(serverId: string): Promise<OAuthAuthorizeResult> {
  return invoke<OAuthAuthorizeResult>("oauth_authorize", { serverId }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

/** Exchanges the authorization code (from the browser redirect) for
 *  tokens and stores them on the server entry. */
export async function exchangeOAuth(serverId: string, code: string, state: string): Promise<void> {
  return invoke<void>("oauth_exchange", { serverId, code, state }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

/** Refreshes the server's access token with its stored refresh token. */
export async function refreshOAuth(serverId: string): Promise<void> {
  return invoke<void>("oauth_refresh", { serverId }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

/** Clears the server's OAuth credentials (logout / re-auth from scratch). */
export async function clearOAuth(serverId: string): Promise<void> {
  return invoke<void>("oauth_clear", { serverId }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}

/** Reads the OAuth credential state of a saved server. */
export async function oauthStatus(serverId: string): Promise<OAuthStatus> {
  return invoke<OAuthStatus>("oauth_status", { serverId }).catch((err: unknown) => {
    throw ApiError.fromUnknown(err);
  });
}
