// Markdown rendering pipeline (TASK-M2-07): a markdown-it singleton
// configured for GFM (tables, strikethrough, task lists, linkify) with raw
// HTML disabled, followed by a DOMPurify pass as the second XSS layer.
//
// Fenced code blocks are emitted as inert placeholders carrying the fence
// info (data-fence-lang) and the source encoded as a URI component
// (data-fence-code); CodeBlock hydrates them with Shiki output after the
// sanitized HTML is attached, so untrusted text never reaches innerHTML
// unsanitized.

import MarkdownIt from "markdown-it";
import type { RendererRule } from "markdown-it";
import taskLists from "markdown-it-task-lists";
import DOMPurify from "dompurify";

/** Selector for the code-fence placeholders emitted by the fence rule. */
export const CODE_FENCE_SELECTOR = "[data-fence-lang]";

/** Escapes text for safe insertion into an HTML attribute value. */
export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const md = new MarkdownIt({
  // Raw HTML is escaped by the parser instead of rendered (XSS layer 1).
  html: false,
  linkify: true,
  typographer: true,
})
  // GFM-ish extras: tables and strikethrough are off by default.
  .enable(["table", "strikethrough"])
  .use(taskLists, { label: false });

// Fence override: emit a placeholder instead of <pre><code> so code blocks
// can be highlighted asynchronously (Shiki loads language packs lazily).
// encodeURIComponent keeps the payload attribute-safe (no quotes or angle
// brackets survive) and data-* attributes pass DOMPurify's allowlist.
md.renderer.rules.fence = ((tokens, idx) => {
  const token = tokens[idx];
  const info = token.info.trim();
  const lang = info.split(/\s+/)[0]?.toLowerCase() ?? "";
  const code = encodeURIComponent(token.content);
  return `<div class="code-fence" data-fence-lang="${escapeHtml(lang)}" data-fence-code="${code}"></div>`;
}) as RendererRule;

// External links open in a new tab with a safe rel; in-page anchors and
// relative links stay as-is.
const defaultLinkOpen = md.renderer.rules.link_open;
md.renderer.rules.link_open = ((tokens, idx, options, _env, self) => {
  const token = tokens[idx];
  const href = String(token.attrGet("href") ?? "");
  if (/^https?:\/\//i.test(href)) {
    token.attrSet("target", "_blank");
    token.attrSet("rel", "noopener noreferrer");
  }
  return defaultLinkOpen
    ? defaultLinkOpen(tokens, idx, options, _env, self)
    : self.renderToken(tokens, idx, options);
}) as RendererRule;

const sanitizeConfig = {
  // Shiki emits per-token colors via style attributes; DOMPurify's default
  // profile would strip them. Style values are URI-scheme checked by
  // DOMPurify and cannot execute scripts in modern engines. checked/disabled
  // belong to the task-list checkboxes, target to the rewritten external
  // links (markdown.ts link_open rule).
  ADD_ATTR: ["style", "checked", "disabled", "target"],
  // Task-list checkboxes are generated by markdown-it-task-lists (raw HTML
  // is disabled, so <input> never originates from untrusted source text).
  ADD_TAGS: ["input"],
};

/**
 * Renders markdown source to sanitized HTML.
 * Layers: markdown-it (html:false + safe link protocols) then DOMPurify.
 */
export function renderMarkdown(source: string): string {
  return DOMPurify.sanitize(md.render(source), sanitizeConfig);
}

/** Decodes a data-fence-code payload back into the fence's source text. */
export function decodeFenceCode(encoded: string): string {
  try {
    return decodeURIComponent(encoded);
  } catch {
    return encoded;
  }
}
