//! Tauri command surface for the transport layer (ADR-002 §6.3), the
//! server registry (TASK-M1-03) and the health monitor (TASK-M1-04). Thin
//! wrappers: the implementation lives in `crate::transport` /
//! `crate::connections` so it can be unit-tested without a Tauri runtime.

use crate::connections::health::{HealthMonitor, ServerHealth};
use crate::connections::local::LocalServerManager;
use crate::connections::registry::{RegistryError, ServerEntry, ServerEntryInput};
use crate::connections::ServerRegistry;
use crate::discovery::{DiscoveredServer, MdnsDiscovery};
use crate::transport::http::{
    http_cancel as cancel_request, http_request as do_request, ApiError, Auth, HttpRequest,
    HttpResponse,
};
use crate::transport::sse::{sse_subscribe as subscribe, sse_unsubscribe as unsubscribe};
use crate::transport::ws::{
    pty_ws_close as close_pty_connection, pty_ws_connect as connect_pty_ws,
    pty_ws_send as send_pty_ws,
};

/// Performs a REST request against an OpenCode server (reqwest / rustls).
/// `serverID`-based requests resolve their base URL through the registry.
#[tauri::command]
pub async fn http_request(
    mut request: HttpRequest,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<HttpResponse, ApiError> {
    resolve_request_url(&mut request, &registry)?;
    do_request(request).await
}

/// Aborts the in-flight request registered under the given request id.
#[tauri::command]
pub fn http_cancel(request_id: String) {
    cancel_request(request_id);
}

/// Subscribes to a server's SSE stream; events arrive on `channel` as single
/// parsed values or 16ms batches of arrays.
#[tauri::command]
pub fn sse_subscribe(
    server_id: String,
    directory: Option<String>,
    channel: tauri::ipc::Channel<serde_json::Value>,
    auth: Option<Auth>,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<u64, ApiError> {
    let base_url = lookup_server_base_url(&server_id, &registry)?;
    subscribe(base_url, directory, channel, auth)
}

/// Stops the subscription with the given id.
#[tauri::command]
pub fn sse_unsubscribe(subscription_id: u64) {
    unsubscribe(subscription_id);
}

/// Opens a PTY WebSocket data channel: fetches a connect ticket through the
/// REST transport, assembles the ws(s) URL and spawns the read loop. Binary
/// frames arrive on `channel` as `{ "bytes": [...] }` envelopes, termination
/// as `{ "type": "pty.ws.closed" }`.
#[tauri::command]
pub async fn pty_ws_connect(
    server_id: String,
    pty_id: String,
    directory: Option<String>,
    channel: tauri::ipc::Channel<serde_json::Value>,
    auth: Option<Auth>,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<u64, ApiError> {
    let base_url = lookup_server_base_url(&server_id, &registry)?;
    connect_pty_ws(base_url, pty_id, directory, channel, auth).await
}

/// Sends one binary frame on the given PTY connection.
#[tauri::command]
pub async fn pty_ws_send(connection_id: u64, data: Vec<u8>) -> Result<(), ApiError> {
    send_pty_ws(connection_id, data).await
}

/// Closes the given PTY connection (idempotent).
#[tauri::command]
pub fn pty_ws_close(connection_id: u64) {
    close_pty_connection(connection_id);
}

/// Lists all saved servers.
#[tauri::command]
pub fn list_servers(registry: tauri::State<'_, ServerRegistry<tauri::Wry>>) -> Vec<ServerEntry> {
    registry.list()
}

/// Saves a new server; id and timestamps are generated by the registry.
#[tauri::command]
pub fn add_server(
    entry: ServerEntryInput,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<ServerEntry, ApiError> {
    registry.add(entry).map_err(map_registry_error)
}

/// Updates the user-supplied fields of an existing server.
#[tauri::command]
pub fn update_server(
    id: String,
    entry: ServerEntryInput,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<ServerEntry, ApiError> {
    registry.update(id, entry).map_err(map_registry_error)
}

/// Removes the server with the given id and stops its health monitor.
#[tauri::command]
pub fn remove_server(
    id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
    monitor: tauri::State<'_, HealthMonitor<tauri::Wry>>,
    local: tauri::State<'_, LocalServerManager>,
) -> Result<(), ApiError> {
    local.stop(&id);
    registry.remove(id.clone()).map_err(map_registry_error)?;
    monitor.stop(&id);
    Ok(())
}

/// Starts the app-managed local `opencode serve` process for a saved server.
#[cfg(desktop)]
#[tauri::command]
pub fn start_local_server(
    server_id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
    local: tauri::State<'_, LocalServerManager>,
) -> Result<u32, ApiError> {
    let entry = registry
        .get(&server_id)
        .ok_or_else(|| ApiError::not_found(format!("server {server_id} not found")))?;
    if entry.mode != crate::connections::registry::ServerMode::Local {
        return Err(ApiError::invalid_url(
            "only local-mode servers can be started by the app",
        ));
    }
    local.start(&server_id).map_err(ApiError::network)
}

/// Stops an app-managed local server. Idempotent for already-exited processes.
#[cfg(desktop)]
#[tauri::command]
pub fn stop_local_server(server_id: String, local: tauri::State<'_, LocalServerManager>) {
    local.stop(&server_id);
}

/// Latest health snapshot of the server, cached by the running monitor.
#[tauri::command]
pub fn get_server_health(
    server_id: String,
    monitor: tauri::State<'_, HealthMonitor<tauri::Wry>>,
) -> Result<ServerHealth, ApiError> {
    monitor
        .get(&server_id)
        .ok_or_else(|| ApiError::not_found(format!("no health state for server {server_id}")))
}

/// One-shot health probe against an arbitrary server URL (Add Server flow);
/// the snapshot carries the outcome (`healthy`/`status`/`failCount`).
#[tauri::command]
pub async fn probe_server(url: String, auth: Option<Auth>) -> Result<ServerHealth, ApiError> {
    Ok(crate::connections::health::probe(url, auth).await)
}

/// Starts the 15s health polling loop for a saved server.
#[tauri::command]
pub fn start_health_monitoring(
    server_id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
    monitor: tauri::State<'_, HealthMonitor<tauri::Wry>>,
) -> Result<(), ApiError> {
    let entry = registry
        .get(&server_id)
        .ok_or_else(|| ApiError::not_found(format!("server {server_id} not found")))?;
    monitor.start(
        server_id,
        entry.url,
        Some(Auth {
            username: entry.username,
            password: entry.password,
            bearer: entry.oauth.as_ref().map(|oauth| oauth.access_token.clone()),
        }),
    );
    Ok(())
}

/// Stops the health polling loop of the given server (idempotent).
#[tauri::command]
pub fn stop_health_monitoring(
    server_id: String,
    monitor: tauri::State<'_, HealthMonitor<tauri::Wry>>,
) -> Result<(), ApiError> {
    monitor.stop(&server_id);
    Ok(())
}

/// Starts the LAN mDNS scan for OpenCode servers (idempotent); every newly
/// discovered server arrives as a `server-discovered` event.
#[tauri::command]
pub fn start_mdns_discovery(
    discovery: tauri::State<'_, MdnsDiscovery<tauri::Wry>>,
) -> Result<(), ApiError> {
    discovery.start();
    Ok(())
}

/// Stops the LAN mDNS scan (idempotent).
#[tauri::command]
pub fn stop_mdns_discovery(
    discovery: tauri::State<'_, MdnsDiscovery<tauri::Wry>>,
) -> Result<(), ApiError> {
    discovery.stop();
    Ok(())
}

/// Servers discovered so far by the LAN mDNS scan.
#[tauri::command]
pub fn get_discovered_servers(
    discovery: tauri::State<'_, MdnsDiscovery<tauri::Wry>>,
) -> Vec<DiscoveredServer> {
    discovery.discovered()
}

/// Resolves the base URL registered for a server id.
#[tauri::command]
pub fn resolve_server_base_url(
    server_id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<String, ApiError> {
    lookup_server_base_url(&server_id, &registry)
}

/// Fills in `request.url` from the registry when only `serverID` is given.
fn resolve_request_url(
    request: &mut HttpRequest,
    registry: &ServerRegistry<tauri::Wry>,
) -> Result<(), ApiError> {
    if request.url.is_none() {
        if let Some(server_id) = &request.server_id {
            request.url = Some(lookup_server_base_url(server_id, registry)?);
        }
    }
    Ok(())
}

fn lookup_server_base_url(
    server_id: &str,
    registry: &ServerRegistry<tauri::Wry>,
) -> Result<String, ApiError> {
    registry
        .resolve_base_url(server_id)
        .ok_or_else(|| ApiError::not_found(format!("server {server_id} not found")))
}

fn map_registry_error(error: RegistryError) -> ApiError {
    match error {
        RegistryError::NotFound(id) => ApiError::not_found(format!("server {id} not found")),
        RegistryError::Persist(message) => ApiError::persist(message),
    }
}

// ---- RFC 9728 OAuth for servers (TASK-UI-01) ----

/// Result of an OAuth discovery: the parsed RFC 9728 metadata, reduced to
/// the fields the frontend needs to build the consent UX.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OAuthDiscovery {
    pub authorization_endpoint: String,
    pub token_endpoint: String,
    pub client_id: Option<String>,
    pub scopes_supported: Option<Vec<String>>,
}

/// Discovers the RFC 9728 OAuth metadata of a server: GET
/// `/.well-known/oauth-authorization-server` (the `www-authenticate`
/// challenge of a 401 points there; the path is also probed directly when
/// the server advertises OAuth). Returns the discovery summary or a
/// classified error (404/network => the server has no OAuth metadata).
#[tauri::command]
pub async fn oauth_discover(url: String) -> Result<OAuthDiscovery, ApiError> {
    let discovery = crate::connections::oauth::discovery_url(&url);
    let request = HttpRequest {
        url: Some(discovery.clone()),
        method: "GET".to_string(),
        path: "".to_string(),
        timeout_ms: Some(10_000),
        ..HttpRequest::default()
    };
    let response = do_request(request).await.map_err(|err| {
        // 404 / 401 mean "not an OAuth-protected server"; surface the raw
        // status so the frontend can distinguish "no OAuth" from "broken".
        if err.status == Some(404) {
            ApiError::not_found("no OAuth discovery document".to_string())
        } else {
            err
        }
    })?;
    let body = response.body_text.unwrap_or_default();
    let metadata = crate::connections::oauth::parse_discovery(&body)
        .map_err(|_| ApiError::invalid_url("invalid OAuth discovery document".to_string()))?;
    Ok(OAuthDiscovery {
        authorization_endpoint: metadata.authorization_endpoint,
        token_endpoint: metadata.token_endpoint,
        client_id: metadata.client_id,
        scopes_supported: metadata.scopes_supported,
    })
}

/// OAuth authorization request: generates a PKCE pair and a state value
/// for the server, persists them in the process-global pending store and
/// returns the authorization URL (the frontend opens it in the system
/// browser) plus the redirect URI the server must be configured to accept
/// and the client id to use. The PKCE verifier never leaves the process:
/// `oauth_exchange` picks it up from the pending store by server id.
#[tauri::command]
pub async fn oauth_authorize(
    server_id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<OAuthAuthorizeResult, ApiError> {
    let entry = registry
        .get(&server_id)
        .ok_or_else(|| ApiError::not_found(format!("server {server_id} not found")))?;
    let discovery_url = crate::connections::oauth::discovery_url(&entry.url);
    // Re-discover on every authorize so endpoint changes are picked up;
    // the entry's stored metadata stays authoritative for requests.
    let metadata = fetch_discovery_metadata(&discovery_url)
        .await
        .map_err(|_| ApiError::network("failed to discover OAuth metadata".to_string()))?;
    let client_id = metadata
        .client_id
        .clone()
        .unwrap_or_else(|| "opencoder-client".to_string());
    let pkce = crate::connections::oauth::generate_pkce();
    let state = format!("oc_{:x}", crate::connections::oauth::now_millis());
    // The redirect URI is a loopback callback the frontend passes on to
    // the authorization server; the fixed port avoids NAT/firewall issues
    // on localhost (RFC 8252 §7.3 prefers loopback with a fixed port).
    let redirect_uri = "http://127.0.0.1:44777/callback".to_string();
    let url = crate::connections::oauth::authorize_url(
        &metadata,
        &client_id,
        &redirect_uri,
        &pkce,
        &state,
        metadata
            .scopes_supported
            .as_ref()
            .map(|scopes| scopes.join(" "))
            .as_deref(),
    )
    .map_err(|err| ApiError::invalid_url(err.to_string()))?;
    pending_oauth::set(
        server_id.clone(),
        pending_oauth::PendingAuth::new(state, pkce),
    );
    Ok(OAuthAuthorizeResult {
        authorization_url: url,
        redirect_uri,
        client_id,
    })
}

/// Result of `oauth_authorize`.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OAuthAuthorizeResult {
    pub authorization_url: String,
    pub redirect_uri: String,
    pub client_id: String,
}

/// Exchanges the authorization code for tokens (authorization code +
/// PKCE grant) and stores them on the server entry. The PKCE verifier and
/// state come from the pending store (set by `oauth_authorize`); a
/// mismatched state aborts the exchange (CSRF defense).
#[tauri::command]
pub async fn oauth_exchange(
    server_id: String,
    code: String,
    state: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<(), ApiError> {
    let pending = pending_oauth::take(&server_id)
        .ok_or_else(|| ApiError::invalid_url("no pending OAuth authorization".to_string()))?;
    if pending.state != state {
        return Err(ApiError::invalid_url("OAuth state mismatch".to_string()));
    }
    let entry = registry
        .get(&server_id)
        .ok_or_else(|| ApiError::not_found(format!("server {server_id} not found")))?;
    let discovery_url = crate::connections::oauth::discovery_url(&entry.url);
    let metadata = fetch_discovery_metadata(&discovery_url)
        .await
        .map_err(|_| ApiError::network("failed to discover OAuth metadata".to_string()))?;
    let client_id = metadata
        .client_id
        .clone()
        .unwrap_or_else(|| "opencoder-client".to_string());
    let redirect_uri = "http://127.0.0.1:44777/callback".to_string();
    let form = crate::connections::oauth::exchange_form(
        &client_id,
        &redirect_uri,
        &code,
        &pending.pkce.verifier,
    );
    let (access, refresh, expires_at, scope) =
        post_token_form(&metadata.token_endpoint, &form).await?;
    registry
        .set_oauth(
            server_id.clone(),
            Some(crate::connections::registry::ServerOAuth {
                client_id,
                discovery_url,
                authorization_endpoint: metadata.authorization_endpoint,
                token_endpoint: metadata.token_endpoint,
                scope,
                access_token: access,
                refresh_token: refresh,
                expires_at,
            }),
        )
        .map_err(map_registry_error)?;
    Ok(())
}

/// Refreshes the server's access token with its stored refresh token
/// (refresh grant, RFC 6749 §6) and updates the stored credentials.
#[tauri::command]
pub async fn oauth_refresh(
    server_id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<(), ApiError> {
    let entry = registry
        .get(&server_id)
        .ok_or_else(|| ApiError::not_found(format!("server {server_id} not found")))?;
    let Some(oauth) = entry.oauth else {
        return Err(ApiError::invalid_url(
            "server has no OAuth credentials".to_string(),
        ));
    };
    let Some(refresh_token) = oauth.refresh_token.clone() else {
        return Err(ApiError::invalid_url(
            crate::connections::oauth::OAuthError::NoRefreshToken.to_string(),
        ));
    };
    let client_id = oauth.client_id.clone();
    let token_endpoint = oauth.token_endpoint.clone();
    let scope = oauth.scope.clone();
    let form = crate::connections::oauth::refresh_form(&client_id, &refresh_token);
    let (access, refresh, expires_at, new_scope) = post_token_form(&token_endpoint, &form).await?;
    registry
        .set_oauth(
            server_id.clone(),
            Some(crate::connections::registry::ServerOAuth {
                client_id,
                discovery_url: oauth.discovery_url,
                authorization_endpoint: oauth.authorization_endpoint,
                token_endpoint,
                scope: new_scope.or(scope),
                access_token: access,
                refresh_token: refresh.or(Some(refresh_token)),
                expires_at,
            }),
        )
        .map_err(map_registry_error)?;
    Ok(())
}

/// Clears the OAuth credentials of a server (logout / re-auth from
/// scratch).
#[tauri::command]
pub fn oauth_clear(
    server_id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<(), ApiError> {
    registry
        .set_oauth(server_id, None)
        .map_err(map_registry_error)
}

/// Whether the server has stored OAuth credentials (used by the frontend
/// to decide between the Basic re-auth form and the OAuth flow).
#[tauri::command]
pub fn oauth_status(
    server_id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<OAuthStatus, ApiError> {
    let entry = registry
        .get(&server_id)
        .ok_or_else(|| ApiError::not_found(format!("server {server_id} not found")))?;
    Ok(OAuthStatus {
        configured: entry.oauth.is_some(),
        has_refresh_token: entry
            .oauth
            .as_ref()
            .map(|oauth| oauth.refresh_token.is_some())
            .unwrap_or(false),
    })
}

/// Summary of a server's OAuth credential state.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OAuthStatus {
    pub configured: bool,
    pub has_refresh_token: bool,
}

/// Fetches and parses the RFC 9728 discovery document at the given URL.
async fn fetch_discovery_metadata(
    discovery_url: &str,
) -> Result<crate::connections::oauth::OAuthServerMetadata, ApiError> {
    let request = HttpRequest {
        url: Some(discovery_url.to_string()),
        method: "GET".to_string(),
        path: "".to_string(),
        timeout_ms: Some(10_000),
        ..HttpRequest::default()
    };
    let response = do_request(request).await?;
    let body = response.body_text.unwrap_or_default();
    crate::connections::oauth::parse_discovery(&body)
        .map_err(|_| ApiError::invalid_url("invalid OAuth discovery document".to_string()))
}

/// POSTs an OAuth form to the token endpoint and parses the response.
async fn post_token_form(
    token_endpoint: &str,
    form: &[(&'static str, String)],
) -> Result<crate::connections::oauth::TokenGrant, ApiError> {
    let form_object = serde_json::json!(form
        .iter()
        .map(|(key, value)| (key, value))
        .collect::<std::collections::HashMap<_, _>>());
    let request = HttpRequest {
        url: Some(token_endpoint.to_string()),
        method: "POST".to_string(),
        path: "".to_string(),
        form: Some(form_object),
        timeout_ms: Some(15_000),
        ..HttpRequest::default()
    };
    let response = do_request(request).await?;
    let text = response.body_text.unwrap_or_default();
    crate::connections::oauth::parse_token_response(&text, crate::connections::oauth::now_millis())
        .map_err(|err| ApiError::invalid_url(err.to_string()))
}

/// In-process store of the pending PKCE/state of an in-flight
/// authorization; one entry per server, replaced on re-authorize.
mod pending_oauth {
    use std::collections::HashMap;
    use std::sync::Mutex;

    use crate::connections::oauth::PkcePair;

    pub(super) struct PendingAuth {
        pub(super) state: String,
        pub(super) pkce: PkcePair,
    }

    impl PendingAuth {
        pub(super) fn new(state: String, pkce: PkcePair) -> Self {
            Self { state, pkce }
        }
    }

    static PENDING: Mutex<Option<HashMap<String, PendingAuth>>> = Mutex::new(None);

    pub(super) fn set(server_id: String, pending: PendingAuth) {
        let mut map = PENDING.lock().unwrap();
        map.get_or_insert_with(HashMap::new)
            .insert(server_id, pending);
    }

    pub(super) fn take(server_id: &str) -> Option<PendingAuth> {
        let mut map = PENDING.lock().unwrap();
        map.as_mut().and_then(|map| map.remove(server_id))
    }
}
