//! Tauri command surface for the transport layer (ADR-002 §6.3), the
//! server registry (TASK-M1-03) and the health monitor (TASK-M1-04). Thin
//! wrappers: the implementation lives in `crate::transport` /
//! `crate::connections` so it can be unit-tested without a Tauri runtime.

use crate::connections::health::{HealthMonitor, ServerHealth};
use crate::connections::registry::{RegistryError, ServerEntry, ServerEntryInput};
use crate::connections::ServerRegistry;
use crate::transport::http::{
    http_cancel as cancel_request, http_request as do_request, ApiError, Auth, HttpRequest,
    HttpResponse,
};
use crate::transport::sse::{sse_subscribe as subscribe, sse_unsubscribe as unsubscribe};

/// Performs a REST request against an OpenCode server (reqwest / rustls).
/// `serverID`-based requests resolve their base URL through the registry.
#[tauri::command]
pub async fn http_request(
    mut request: HttpRequest,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<HttpResponse, ApiError> {
    resolve_request_url(&mut request, &registry)?;
    do_request(request).await
}

/// Aborts the in-flight request registered under the given request id.
#[tauri::command]
pub fn http_cancel(request_id: String) {
    cancel_request(request_id);
}

/// Subscribes to a server's SSE stream; events arrive on `channel` as single
/// parsed values or 16ms batches of arrays.
#[tauri::command]
pub fn sse_subscribe(
    server_id: String,
    directory: Option<String>,
    channel: tauri::ipc::Channel<serde_json::Value>,
    auth: Option<Auth>,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<u64, ApiError> {
    let base_url = lookup_server_base_url(&server_id, &registry)?;
    subscribe(base_url, directory, channel, auth)
}

/// Stops the subscription with the given id.
#[tauri::command]
pub fn sse_unsubscribe(subscription_id: u64) {
    unsubscribe(subscription_id);
}

/// Lists all saved servers.
#[tauri::command]
pub fn list_servers(registry: tauri::State<'_, ServerRegistry<tauri::Wry>>) -> Vec<ServerEntry> {
    registry.list()
}

/// Saves a new server; id and timestamps are generated by the registry.
#[tauri::command]
pub fn add_server(
    entry: ServerEntryInput,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<ServerEntry, ApiError> {
    registry.add(entry).map_err(map_registry_error)
}

/// Updates the user-supplied fields of an existing server.
#[tauri::command]
pub fn update_server(
    id: String,
    entry: ServerEntryInput,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<ServerEntry, ApiError> {
    registry.update(id, entry).map_err(map_registry_error)
}

/// Removes the server with the given id and stops its health monitor.
#[tauri::command]
pub fn remove_server(
    id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
    monitor: tauri::State<'_, HealthMonitor<tauri::Wry>>,
) -> Result<(), ApiError> {
    registry.remove(id.clone()).map_err(map_registry_error)?;
    monitor.stop(&id);
    Ok(())
}

/// Latest health snapshot of the server, cached by the running monitor.
#[tauri::command]
pub fn get_server_health(
    server_id: String,
    monitor: tauri::State<'_, HealthMonitor<tauri::Wry>>,
) -> Result<ServerHealth, ApiError> {
    monitor
        .get(&server_id)
        .ok_or_else(|| ApiError::not_found(format!("no health state for server {server_id}")))
}

/// One-shot health probe against an arbitrary server URL (Add Server flow);
/// the snapshot carries the outcome (`healthy`/`status`/`failCount`).
#[tauri::command]
pub async fn probe_server(url: String, auth: Option<Auth>) -> Result<ServerHealth, ApiError> {
    Ok(crate::connections::health::probe(url, auth).await)
}

/// Starts the 15s health polling loop for a saved server.
#[tauri::command]
pub fn start_health_monitoring(
    server_id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
    monitor: tauri::State<'_, HealthMonitor<tauri::Wry>>,
) -> Result<(), ApiError> {
    let entry = registry
        .get(&server_id)
        .ok_or_else(|| ApiError::not_found(format!("server {server_id} not found")))?;
    monitor.start(
        server_id,
        entry.url,
        Some(Auth {
            username: entry.username,
            password: entry.password,
        }),
    );
    Ok(())
}

/// Stops the health polling loop of the given server (idempotent).
#[tauri::command]
pub fn stop_health_monitoring(
    server_id: String,
    monitor: tauri::State<'_, HealthMonitor<tauri::Wry>>,
) -> Result<(), ApiError> {
    monitor.stop(&server_id);
    Ok(())
}

/// Resolves the base URL registered for a server id.
#[tauri::command]
pub fn resolve_server_base_url(
    server_id: String,
    registry: tauri::State<'_, ServerRegistry<tauri::Wry>>,
) -> Result<String, ApiError> {
    lookup_server_base_url(&server_id, &registry)
}

/// Fills in `request.url` from the registry when only `serverID` is given.
fn resolve_request_url(
    request: &mut HttpRequest,
    registry: &ServerRegistry<tauri::Wry>,
) -> Result<(), ApiError> {
    if request.url.is_none() {
        if let Some(server_id) = &request.server_id {
            request.url = Some(lookup_server_base_url(server_id, registry)?);
        }
    }
    Ok(())
}

fn lookup_server_base_url(
    server_id: &str,
    registry: &ServerRegistry<tauri::Wry>,
) -> Result<String, ApiError> {
    registry
        .resolve_base_url(server_id)
        .ok_or_else(|| ApiError::not_found(format!("server {server_id} not found")))
}

fn map_registry_error(error: RegistryError) -> ApiError {
    match error {
        RegistryError::NotFound(id) => ApiError::not_found(format!("server {id} not found")),
        RegistryError::Persist(message) => ApiError::persist(message),
    }
}
